name: cg-gnn
channels:
  - defaults
dependencies:
  - dglteam::dgl-cuda11.8
  - h5py
  - matplotlib
  - numpy
  - nvidia::cuda-toolkit=11.8
  - pandas
  - pytables
  - python
  - pytorch::pytorch-cuda=11.8
  - scikit-learn
  - scipy
  - tqdm
  - pip:
    - spatialprofilingtoolbox[cggnn]
