name: cg-gnn
channels:
  - defaults
  - nvidia/label/cuda-11.8.0
  - dglteam/label/cu118
dependencies:
  - python==3.11
  - pip
  - h5py
  - matplotlib
  - numpy
  - pandas
  - pytables
  - cudatoolkit
  - pytorch::pytorch
  - pytorch::pytorch-cuda=11.8
  - dgl
  - scikit-learn
  - scipy
  - tqdm
  # Development dependencies
  - autopep8
  - pylint
